const directory = [
  { name: "Aaron Iker", twitter: "aaroniker_me" },
  { name: "Cassandra Paigee", twitter: "CassandraPaigee" },
  { name: "Cassie Evans", twitter: "cassiecodes" },
  { name: "Adam Kuhn", twitter: "cobra_winfrey" },
  { name: "Tee Diang", twitter: "cybercountess" },
  { name: "Derya Tanrıverdi", twitter: "Derya_T88" },
  { name: "Jhey Tompkins", twitter: "jh3yy" },
  { name: "Olivia Ng", twitter: "meowlivia_" },
  { name: "Pete Barr", twitter: "petebarr" },
  { name: "Kyle Shook", twitter: "elyktrix" },
  { name: "Michelle Barker", twitter: "MicheBarks" },
  { name: "Ilithya", twitter: "ilithya_net" },
  { name: "Yuan Chuan", twitter: "yuanchuan23" },
  { name: "Christina Gorton", twitter: "coffeecraftcode" },
  { name: "Liam Egan", twitter: "liamegan" },
  { name: "Kristopher Van Sant", twitter: "rosieebob" },
  { name: "Steve Gardner", twitter: "steeevg" },
  { name: "Ben Evans", twitter: "ivorjetski" },
  { name: "Milan Raring", twitter: "MilanRaring" },
  { name: "Florin Pop", twitter: "florinpop1705" },
  { name: "Erica Anderson", twitter: "ericaofanderson" },
  { name: "Étienne Jacob", twitter: "etiennejcb" },
  { name: "Jamie Coulter", twitter: "jamiecoulter89" },
  { name: "Yusuke Nakaya", twitter: "s14garnet" },
  { name: "John Beech", twitter: "Johnee_B" },
  { name: "Flopine", twitter: "FlopineYeah" },
  { name: "Keita Abe", twitter: "su8erlemon" },
  { name: "Matt Zucker", twitter: "matt_zucker" },
  { name: "Thomas Hooper", twitter: "tdhooper" },
  { name: "Kuva (Studio)", twitter: "wearekuva" },
  { name: "かねた", twitter: "kanetaaaaa" },
  { name: "おかず", twitter: "okazz_" },
  { name: "Natalia Zmysłowska", twitter: "CodeMeNatalie" },
  { name: "Tiffany Choong", twitter: "tiffachooo" },
  { name: "Daniel Shiffman", twitter: "shiffman" },
  { name: "David Khourshid", twitter: "DavidKPiano" },
  { name: "Agathe", twitter: "agathacco" },
  { name: "Ana Tudor", twitter: "anatudor" },
  { name: "Katherine Kato", twitter: "kato_katherine" },
  { name: "Sarah Drasner", twitter: "sarah_edo" },
  { name: "Charlie Gerard", twitter: "devdevcharlie" },
  { name: "Diana Smith", twitter: "cyanharlow" },
  { name: "Chris Dolphin", twitter: "LikeTheMammal" },
  { name: "Mandy Kerr", twitter: "Mandy_Kerr" }
]
module.exports = directory
