const directory = [
  { name: "Aaron Iker", twitter: "aaroniker_me" },
  { name: "Adam Kuhn", twitter: "cobra_winfrey" },
  { name: "Agathe", twitter: "agathacco" },
  { name: "Algorigraph", twitter: "algorigraph" },
  { name: "Ana Tudor", twitter: "anatudor" },
  { name: "Andreas Refsgaard", twitter: "AndreasRef" },
  { name: "Ben Evans", twitter: "ivorjetski" },
  { name: "Cassandra Paigee", twitter: "CassandraPaigee" },
  { name: "Cassie Evans", twitter: "cassiecodes" },
  { name: "Cassie Tarakajian", twitter: "hellothisiscass" },
  { name: "Charlie Gerard", twitter: "devdevcharlie" },
  { name: "Chris Dolphin", twitter: "LikeTheMammal" },
  { name: "Christina Gorton", twitter: "coffeecraftcode" },
  { name: "Cris Valenzuela", twitter: "c_valenzuelab" },
  { name: "Daniel Shiffman", twitter: "shiffman" },
  { name: "Dave Whyte", twitter: "beesandbombs" },
  { name: "David Khourshid", twitter: "DavidKPiano" },
  { name: "Derya Tanrıverdi", twitter: "Derya_T88" },
  { name: "Diana Smith", twitter: "cyanharlow" },
  { name: "Erica Anderson", twitter: "ericaofanderson" },
  { name: "Étienne Jacob", twitter: "etiennejcb" },
  { name: "Flopine", twitter: "FlopineYeah" },
  { name: "Florin Pop", twitter: "florinpop1705" },
  { name: "Gene Kogan", twitter: "genekogan" },
  { name: "Ilithya", twitter: "ilithya_net" },
  { name: "Jacob Joaquin", twitter: "jacobjoaquin" },
  { name: "Jamie Coulter", twitter: "jamiecoulter89" },
  { name: "Jhey Tompkins", twitter: "jh3yy" },
  { name: "John Beech", twitter: "Johnee_B" },
  { name: "Jose Blanco Perales", twitter: "blancoperales" },
  { name: "Katherine Kato", twitter: "kato_katherine" },
  { name: "Keita Abe", twitter: "su8erlemon" },
  { name: "Kristopher Van Sant", twitter: "rosieebob" },
  { name: "Kuva (Studio)", twitter: "wearekuva" },
  { name: "Kyle Shook", twitter: "elyktrix" },
  { name: "Lia", twitter: "liasomething" },
  { name: "Liam Egan", twitter: "liamegan" },
  { name: "Mandy Kerr", twitter: "Mandy_Kerr" },
  { name: "Manoloide", twitter: "manoloidee" },
  { name: "Marta Verde", twitter: "GreenMartinha" },
  { name: "Matt DesLauriers", twitter: "mattdesl" },
  { name: "Matt Zucker", twitter: "matt_zucker" },
  { name: "Michelle Barker", twitter: "MicheBarks" },
  { name: "Milan Raring", twitter: "MilanRaring" },
  { name: "Natalia Zmysłowska", twitter: "CodeMeNatalie" },
  { name: "Olivia Ng", twitter: "meowlivia_" },
  { name: "Patricio Gonzalez Vivo", twitter: "patriciogv" },
  { name: "Peder Norrby", twitter: "algomystic" },
  { name: "Pete Barr", twitter: "petebarr" },
  { name: "Ricardo Cabello", twitter: "mrdoob" },
  { name: "Sarah Drasner", twitter: "sarah_edo" },
  { name: "Saskia Freeke", twitter: "sasj_nl" },
  { name: "Steve Gardner", twitter: "steeevg" },
  { name: "Tee Diang", twitter: "cybercountess" },
  { name: "Thomas Hooper", twitter: "tdhooper" },
  { name: "Thomas Wang", twitter: "thomaswangio" },
  { name: "Tiffany Choong", twitter: "tiffachooo" },
  { name: "Tim Rodenbröker", twitter: "timrodenbroeker" },
  { name: "Tyler Hobbs", twitter: "tylerxhobbs" },
  { name: "Yuan Chuan", twitter: "yuanchuan23" },
  { name: "Yusuke Nakaya", twitter: "s14garnet" },
  { name: "Zach Lieberman", twitter: "zachlieberman" },
  { name: "おかず", twitter: "okazz_" },
  { name: "かねた", twitter: "kanetaaaaa" }
];
module.exports = directory;
